//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobileHR.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentHistoryEducation
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAdress { get; set; }
        public string CertificateName { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Comments { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
