//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobileHR.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permissions()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> ShowEmployees { get; set; }
        public Nullable<bool> EditEmployees { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> ShowContracts { get; set; }
        public Nullable<bool> DeleteContracts { get; set; }
        public Nullable<bool> ShowPositions { get; set; }
        public Nullable<bool> EditPositions { get; set; }
        public Nullable<bool> ShowDepartments { get; set; }
        public Nullable<bool> EditDepartments { get; set; }
        public Nullable<bool> ShowOrganizationStructure { get; set; }
        public Nullable<bool> ShowSalary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
